# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{openid_auth}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Travis Reeder"]
  s.date = %q{2009-12-02}
  s.description = %q{Simple way to add openid to rails apps.}
  s.email = %q{travis@appoxy.com}
  s.extra_rdoc_files = [
    "CHANGELOG",
     "README.markdown"
  ]
  s.files = [
    "lib/open_id_authentication.rb",
     "lib/open_id_authentication/association.rb",
     "lib/open_id_authentication/db_store.rb",
     "lib/open_id_authentication/nonce.rb",
     "lib/open_id_authentication/request.rb",
     "lib/open_id_authentication/timeout_fixes.rb"
  ]
  s.homepage = %q{http://github.com/appoxy/open_id_authentication}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple way to add openid to rails apps.}
  s.test_files = [
    "test/normalize_test.rb",
     "test/open_id_authentication_test.rb",
     "test/status_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-openid>, [">= 0"])
    else
      s.add_dependency(%q<ruby-openid>, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby-openid>, [">= 0"])
  end
end

